[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jupyter-quant"
dynamic = ["version"]
authors = [{ name = "gnzsnz" }]
description = "Jupyter quant research environment. "
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE.txt" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "alphalens-reloaded==0.4.5",
    "arch==7.1.0",
    "black==24.8.0",
    "bottleneck==1.4.0",
    "dask[dataframe,distributed]==2024.9.0",
    "empyrical-reloaded==0.5.10",
    "exchange_calendars==4.5.6",
    "h5py==3.12.1",
    "hurst==0.0.5",
    "ib-fundamental==0.0.5",
    "ib_async==1.0.3",
    "ipympl==0.9.4",
    "ipywidgets==8.1.5",
    "isort==5.13.2",
    "jedi-language-server==0.41.4",
    "jupyterlab==4.2.5",
    "jupyterlab-lsp==5.1.0",
    "jupyterlab_code_formatter==3.0.2",
    "jupyterlab_widgets==3.0.13",
    "lightgbm==4.5.0",
    "matplotlib==3.9.2",
    "numba==0.60.0",
    "numexpr==2.10.1",
    "numpy==1.26.4",
    "optuna==4.0.0",
    "pandas==2.2.3",
    "patsy==0.5.6",
    "pip==24.2",
    "py_vollib==1.0.1",
    "py_vollib_vectorized==0.1.1",
    "pyarrow==17.0.0",
    "pyfolio-reloaded==0.9.8",
    "pykalman==0.9.7",
    "PyPortfolioOpt==1.5.5",
    "quantstats-lumi==0.3.3",
    "scikit-learn==1.5.2",
    "scipy==1.14.1",
    "sdepy==1.2.0",
    "seaborn==0.13.2",
    "shap==0.46.0",
    "statsmodels==0.14.3",
    "TA-Lib==0.4.32",
    "tzdata==2024.2",
    "yellowbrick==1.5",
    "yfinance==0.2.43",
    "zipline-reloaded==3.0.4",
]

[project.optional-dependencies]
sk-util = ["skfolio==0.4.0", "sktime==0.33.0"]
bayes = [
    "arviz==0.19.0",
    "bambi==0.14.0",
    "pymc==5.16.2",
    "formulae==0.5.4",
    "graphviz==0.20.3",
]
dev = ["pre-commit>=3.7.1", "build", "wheel"]

[project.urls]
"Homepage" = "https://github.com/quantbelt/jupyter-quant"
"Bug Tracker" = "https://github.com/quantbelt/jupyter-quant/issues"

[tool.setuptools]
packages = ["jupyter_quant"]

[tool.setuptools.dynamic]
version = {attr = "jupyter_quant.__version__"}
