[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jupyter-quant"
dynamic = ["version"]
authors = [{ name = "gnzsnz" }]
description = "Jupyter quant research environment. "
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE.txt" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "alphalens-reloaded==0.4.5",
    "arch==7.2.0",
    "black==25.1.0",
    "bottleneck==1.4.2",
    "dask[dataframe,distributed]==2025.3.0",
    "empyrical-reloaded==0.5.11",
    "exchange_calendars==4.10",
    "h5py==3.13.0",
    "hurst==0.0.5",
    "ib-fundamental==0.0.5",
    "ib_async==1.0.3",
    "ipympl==0.9.7",
    "ipywidgets==8.1.6",
    "isort==6.0.1",
    "jedi-language-server==0.44.0",
    "jupyterlab==4.3.6",
    "jupyterlab-lsp==5.1.0",
    "jupyterlab_code_formatter==3.0.2",
    "jupyterlab_widgets==3.0.14",
    "lightgbm==4.6.0",
    "matplotlib==3.10.1",
    "numba==0.61.2",
    "numexpr==2.10.2",
    "numpy==2.1.3",
    "optuna==4.3.0",
    "pandas==2.2.3",
    "patsy==1.0.1",
    "pip==25.0.1",
    "py_vollib==1.0.1",
    "py_vollib_vectorized==0.1.1",
    "pyarrow==19.0.1",
    "pyfolio-reloaded==0.9.8",
    "pykalman==0.10.1",
    "PyPortfolioOpt==1.5.6",
    "quantstats-lumi==0.3.3",
    "scikit-learn==1.6.1",
    "scipy==1.15.2",
    "sdepy==1.2.0",
    "seaborn==0.13.2",
    "shap==0.47.1",
    "statsmodels==0.14.4",
    "TA-Lib==0.6.3",
    "tzdata==2025.2",
    "yellowbrick==1.5",
    "yfinance==0.2.55",
    "zipline-reloaded==3.1",
]

[project.optional-dependencies]
sk-util = ["skfolio==0.9.0", "sktime==0.37.0"]
bayes = [
    "arviz==0.21.0",
    "bambi==0.15.0",
    "pymc==5.22.0",
    "formulae==0.5.4",
    "graphviz==0.20.3",
]
dev = ["pre-commit>=3.7.1", "build", "wheel", "twine"]

[project.urls]
"Homepage" = "https://github.com/quantbelt/jupyter-quant"
"Bug Tracker" = "https://github.com/quantbelt/jupyter-quant/issues"

[tool.setuptools]
packages = ["jupyter_quant"]

[tool.setuptools.dynamic]
version = {attr = "jupyter_quant.__version__"}
