version: "3.6"
services:
  jupyter-quant:
    build:
      context: .
      platforms:
        - "linux/amd64"
        #- "linux/arm64"
      args:
        USER: ${USER}
        USER_ID: ${USER_ID}
        USER_GID: ${USER_GID}
        IMG_PYTHON_VERSION: ${IMG_PYTHON_VERSION}
        APT_PROXY: ${APT_PROXY}
    image: gnzsnz/jupyter-quant:${IMAGE_VERSION}
    environment:
      APT_PROXY: ${APT_PROXY}
      BYODF: ${BYODF:-}
      SSH_KEYDIR: ${SSH_KEYDIR:-}
      # START_SCRIPTS: ${START_SCRIPTS:-}
      # SSH_PASSPHRASE: ${SSH_PASSPHRASE:-}
      # SSH_PASSPHRASE_FILE: ${SSH_PASSPHRASE_FILE:-}
      TZ: ${QUANT_TZ:-}
    restart: unless-stopped
    ports:
      - ${LISTEN_PORT}:8888
    volumes:
      - quant_conf:/home/${USER}/.config
      - quant_data:/home/${USER}/.local
      - ${PWD}/Notebooks:/home/${USER}/Notebooks
    # secrets:
    #   - ssh_passphrase

volumes:
  quant_conf:
  quant_data:

# secrets:
#   ssh_passphrase:
#     file: pass/ssh_password.txt
